module.exports = Object.freeze({
  CALCULATING_LOAN_INTEREST: "Calculating loan interest",
  CALCULATING_DEPOSIT_INTEREST: "Calculating deposit interest",
  NUMBER_OF_MONTH_IN_YEAR: 12,
  MONTHLY_PAYMENT: 8000000,
  NUMBER_OF_WEEK_IN_YEAR: 52,
  DEPOSIT_TYPE: {
    DEPOSIT_BY_1WEEK: "1 week",
    DEPOSIT_BY_2WEEK: "2 week",
    DEPOSIT_BY_3WEEK: "3 week",
    DEPOSIT_BY_1MONTH: "1 month",
    DEPOSIT_BY_2MONTH: "2 month",
    DEPOSIT_BY_3MONTH: "3 month",
    DEPOSIT_BY_4MONTH: "4 month",
    DEPOSIT_BY_5MONTH: "5 month",
    DEPOSIT_BY_6MONTH: "6 month",
    DEPOSIT_BY_7MONTH: "7 month",
    DEPOSIT_BY_8MONTH: "8 month",
    DEPOSIT_BY_9MONTH: "9 month",
    DEPOSIT_BY_10MONTH: "10 month",
    DEPOSIT_BY_11MONTH: "11 month",
    DEPOSIT_BY_12MONTH: "12 month",
    DEPOSIT_BY_13MONTH: "13 month",
    DEPOSIT_BY_14MONTH: "14 month",
    DEPOSIT_BY_15MONTH: "15 month",
    DEPOSIT_BY_18MONTH: "18 month",
    DEPOSIT_BY_19MONTH: "19 month",
    DEPOSIT_BY_20MONTH: "20 month",
    DEPOSIT_BY_24MONTH: "24 month",
    DEPOSIT_BY_25MONTH: "25 month",
    DEPOSIT_BY_36MONTH: "36 month",
  },
});
